ENV: prod

POSTGRES_ENDPOINT: 'localhost'
POSTGRES_DATABASE: 'itsmyskool_prod'
POSTGRES_USERNAME: 'postgres'
POSTGRES_PASSWORD: 'itsmyskool'
POSTGRES_PORT: '5432'
POSTGRES_SSL: 'false'

JWT_SECRET: 'what-should-i-put-here'
JWT_ADMIN_EXPIRY_TIME: '8h'
